# Generated by Django 5.2.7 on 2025-10-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_tenantinvitation"),
        ("properties", "0002_building_unit_equipment_meter_meterreading"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="properties.unit",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="property",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="properties.unit",
            ),
        ),
    ]
