# Generated by hand to align DB with updated RentalAgreement model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="start_date",
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="end_date",
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="coop_fee",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="electricity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="gas",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="other_fees",
            field=models.FloatField(default=0.0),
        ),
    ]
