# Generated by hand: add optional Unit relation to RentalAgreement
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0003_update_rentalagreement_fields"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="unit",
            field=models.ForeignKey(
                to="properties.unit",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                help_text="Select the specific unit/apartment for this agreement (optional)",
            ),
        ),
    ]
