# Generated by hand: make RentalAgreement.property optional (null/blank)
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_rentalagreement_unit"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="property",
            field=models.ForeignKey(
                to="properties.property",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]
