# Generated by Django 5.2.7 on 2025-10-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_alter_rentalagreement_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='base_rent',
            field=models.FloatField(help_text='Base monthly payment to the landlord'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='coop_fee',
            field=models.FloatField(default=0.0, help_text='Monthly payment for housing cooperative'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='electricity',
            field=models.FloatField(default=0.0, help_text='Estimated monthly electricity bill'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='gas',
            field=models.FloatField(default=0.0, help_text='Estimated monthly gas bill'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='other_fees',
            field=models.FloatField(default=0.0, help_text='Other/extra monthly payments'),
        ),
    ]
