# Generated by Django 5.2.3 on 2025-06-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("properties", "0001_initial"),
        ("users", "0003_landlord_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.tenant"
            ),
        ),
    ]
