# Generated by Django 5.2.7 on 2025-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_landlord_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='tax_residency_country',
            field=models.CharField(default='PL', max_length=2),
        ),
    ]
