# Generated by Django 5.2.3 on 2025-06-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="property",
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="property",
            name="landlord",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="property",
        ),
        migrations.RemoveField(
            model_name="rentalagreement",
            name="property",
        ),
        migrations.RemoveField(
            model_name="rentalagreement",
            name="tenant",
        ),
    ]
