# Generated by Django 5.2.3 on 2025-06-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_maintenancerequest_property_and_more"),
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="rental_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leases.rentalagreement"
            ),
        ),
        migrations.DeleteModel(
            name="MaintenanceRequest",
        ),
        migrations.DeleteModel(
            name="Reminder",
        ),
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.DeleteModel(
            name="RentalAgreement",
        ),
    ]
