# Generated by Django 5.2.7 on 2025-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_payment_rental_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tax_amount',
            field=models.FloatField(default=0.0, help_text='Computed tax for this month based on base_rent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_rate',
            field=models.FloatField(default=0.0, help_text='Effective tax rate for this month (fraction, e.g., 0.085 for 8.5%)'),
        ),
    ]
