# Generated by Junie to preserve Payment history when RentalAgreement is deleted
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_payment_tax_amount_payment_tax_rate"),
        ("leases", "0006_alter_rentalagreement_base_rent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="rental_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                to="leases.rentalagreement",
                null=True,
                blank=True,
            ),
        ),
    ]
