# Generated by Django 5.2.3 on 2025-06-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_landlord_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("area_m2", models.FloatField()),
                ("current_rent", models.FloatField()),
                ("additional_costs", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Available"),
                            (2, "Rented"),
                            (3, "Under Maintenance"),
                            (4, "Unavailable"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.landlord"
                    ),
                ),
            ],
        ),
    ]
