# Generated by Django 5.2.7 on 2025-10-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("users", "0003_landlord_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "landlord",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buildings", to="users.landlord"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(help_text="Unit number or name", max_length=50)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("area_m2", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[("apartment", "Apartment"), ("office", "Office"), ("other", "Other")],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Under Maintenance"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="properties.building"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to="properties.unit"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meter_type",
                    models.CharField(
                        choices=[("water", "Water"), ("electricity", "Electricity"), ("gas", "Gas"), ("heat", "Heat")],
                        max_length=20,
                    ),
                ),
                ("serial", models.CharField(max_length=50)),
                (
                    "unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="meters", to="properties.unit"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeterReading",
            options={"ordering": ["-date"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "meter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="readings", to="properties.meter"),
                ),
            ],
        ),
    ]
